jobs:
  include:
    - stage: unit test
      language: python
      catch: pip
      python:
        - "3.6"
      # command to install dependencies
      install:
        - pip install -r requirements.txt
        - pip install .
      # command to run tests
      script: pytest

    - stage: build frontend
      if: type = push
      language: node_js
      node_js:
        - "10"
      cache:
        yarn: true
        directories: node_modules
      install:
        - cd fe
        - npm install
      script:
        - npm run build

    